services:
  - type: web
    name: english-proficiency-test
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false # Set this manually in Render dashboard
    healthCheckPath: /
    numInstances: 1
    regions:
      - oregon
    scaling:
      minInstances: 0
      maxInstances: 1